version: '3.8'
services:
  app1:
    build: .
    ports:
      - "8081:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=172.27.175.161:9092
      - APP_INSTANCE=1
    networks:
      - my-network
    command: ["--port", "8081"]

  app2:
    build: .
    ports:
      - "8082:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=172.27.175.161:9092
      - APP_INSTANCE=2
    networks:
      - my-network
    command: ["--port", "8082"]

  app3:
    build: .
    ports:
      - "8083:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=172.27.175.161:9092
      - APP_INSTANCE=3
    networks:
      - my-network
    command: ["--port", "8083"]

  app4:
    build: .
    ports:
      - "8084:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=172.27.175.161:9092
      - APP_INSTANCE=4
    networks:
      - my-network
    command: ["--port", "8084"]

  app5:
    build: .
    ports:
      - "8085:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=172.27.175.161:9092
      - APP_INSTANCE=5
    networks:
      - my-network
    command: ["--port", "8085"]

networks:
  my-network:
    driver: bridge
